# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "SPSS hulp"
  url = "#spss-hulp"
  weight = 10

[[main]]
  name = "STATA hulp"
  url = "#stata-hulp"
  weight = 20

[[main]]
  name = "Tarieven"
  url = "#tarieven"
  weight = 30

[[main]]
  name = "Voor studenten"
  url = "#voor-studenten"
  weight = 40

[[main]]
  name = "Voor tutors"
  url = "#voor-studenten"
  weight = 50

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 60

# [[main]]
#   name = ""
#   pre = '<button type="button">Plan a free meeting!</button>'
#   url = "#free-meeting"
#   weight = 100

# [[main]]
#   [cta]
#     url = "https://..."
#     label = "Plan a free meeting!"
#     icon_pack = "fas"
#     icon = "phone"

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70

